### ISSUE TITLE
How to config in the Ubuntu to finish this lab?

### ISSUE THREAD

**Issue by hylinux1024** [eric-keller/npp-linux-01-intro#1]
How to config in the Ubuntu to finish this lab?

I don't have windows

**Comment by GRMCB** [comment]
There are lots of resources online. Have you tried them?

I have a MAC and had to Google a little to get this working.

**Comment by eric-keller** [comment]
The lab isn't dependent on Windows.  VirtualBox and vagrant both work on various Linux distributions.  I think with those, the Vagrantfile won't need to change, and nothing about the lab would need to change.  If you don't want to use VirtualBox, vagrant supports other hypervisors.  The Vagrantfile will need to change slightly - with some config that's specific to the provider.  

https://www.virtualbox.org/wiki/Linux_Downloads
https://developer.hashicorp.com/vagrant/docs/installation
